# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Start development server
        run: npm run dev &
      - name: Wait for server to start
        run: |
          n=0
          until [ $n -ge 5 ]
          do
            curl -sSf http://localhost:3000 && break
            n=$((n+1))
            sleep 10
          done
          if [ $n -eq 5 ]; then
            echo "Error: Failed to start the development server"
            exit 1
          fi
      - name: Run tests
        run: npm run test || exit 1
      - name: Cleanup
        run: npm run cleanup
